### ISSUE TITLE
Unhandled Exception When Opening "UnitTypeTokens"

### ISSUE THREAD

**Issue by Sireyn** [enohka/moddingSuite#18]
As of 0.8.4, attempting to open "UnitTypeTokens" on any unit, on any NDF_Win.dat causes an exception to be thrown. This is with existing populated lists, not null references. All other similar lists I've tried function properly.

pc/ndf/patchable/gfx/everything.ndfbin -> TUniteAuSolDescriptor -> UnitTypeTokens

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at moddingSuite.ViewModel.Ndf.NdfObjectViewModel.isTable(NdfCollection collection)
>    at moddingSuite.ViewModel.Ndf.NdfObjectViewModel.FollowList(IValueHolder prop)
>    at moddingSuite.ViewModel.Ndf.NdfObjectViewModel.DetailsCommandExecute(Object obj)
>    at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
>    at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by enohka** [comment]
resolved, bug came due to "isTable" in NdfObjectViewModel introduces by a commit from Gronak
