### ISSUE TITLE
Steel Division 2

### ISSUE THREAD

**Issue by zomba69** [enohka/moddingSuite#25]
Hi,

Do you think moddingSuite could work with Steel Division 2? With current 0.9 version I can open list of files, but I cant open any dialogue to change them.

Many thanks

**Comment by unitasu11** [comment]
be happy on me it crash with error:)

ya so it would be nice to have modding suite for steel dev 2 (working once:D)

**Comment by enohka** [comment]
Unfortunatley I do not own the game so I can not test this. Might look into it at some point
