### ISSUE TITLE
Confusion in GPL version.

### ISSUE THREAD

**Issue by RemiGC** [enohka/moddingSuite#38]
The LICENSE file included is GPL version 2, while the README.md talk about version 3.

**Comment by enohka** [comment]
Thats true, I would actually like to switch to MIT License. Any concerns?

**Comment by RemiGC** [comment]
I didn't merge anything yet, I don't have a vote on this. :)

I don't have any preference for license on this sort of project. Only that's it's consistent.

**Comment by YoRyan** [comment]
> Thats true, I would actually like to switch to MIT License. Any concerns?

For the record, that's fine by me!

**Comment by enohka** [comment]
Okay, I did the switch.
